# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('lk_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='project.Skill', verbose_name='\u041d\u0430\u0432\u044b\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='lkuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='project.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='lkuser',
            name='want_join',
            field=models.ManyToManyField(blank=True, to='project.Team', verbose_name='\u0412 \u043a\u0430\u043a\u0438\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u044b \u0445\u043e\u0447\u0435\u0442 \u0432\u0441\u0442\u0443\u043f\u0438\u0442\u044c'),
        ),
    ]
