# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk_user', '0002_auto_20170907_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkuser',
            old_name='sername',
            new_name='last_name',
        ),
    ]
