# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk_user', '0003_auto_20170905_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkuser',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='C\u043a\u0440\u044b\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443'),
        ),
        migrations.AlterField(
            model_name='lkuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
    ]
