# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk_user', '0005_remove_lkuser_last_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lkuser',
            index=models.Index(fields=['email'], name='lk_user_lku_email_108df2_idx'),
        ),
        migrations.AddIndex(
            model_name='lkuser',
            index=models.Index(fields=['is_hidden', 'name'], name='lk_user_lku_is_hidd_275426_idx'),
        ),
    ]
