# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lk_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk_user.LkUser', verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u044b\u0442',
                'verbose_name_plural': '\u041e\u043f\u044b\u0442',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0432\u044b\u043a',
                'verbose_name_plural': '\u041d\u0430\u0432\u044b\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u041d\u0430\u0432\u044b\u043a\u043e\u0432',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u041d\u0430\u0432\u044b\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('is_hidden', models.BooleanField(default=False)),
                ('creater_id', models.PositiveIntegerField()),
                ('want_accept', models.ManyToManyField(blank=True, null=True, related_name='want_accept_member', to='lk_user.LkUser', verbose_name='\u041a\u043e\u0433\u043e \u0445\u043e\u0442\u044f\u0442 \u043f\u0440\u0438\u043d\u044f\u0442\u044c \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0443')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430',
                'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.SkillGroup', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
