# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170913_0108'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='project_tea_name_cce6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_hidden', 'member_count'], name='project_tea_is_hidd_391e61_idx'),
        ),
    ]
