# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170914_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='avatar'),
        ),
    ]
