# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20171005_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'verbose_name': '\u0414\u0435\u0434\u043b\u0430\u0439\u043d', 'verbose_name_plural': '\u0414\u0435\u0434\u043b\u0430\u0439\u043d'},
        ),
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043f\u0440\u043e\u0444\u0438\u043b\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u044b'),
        ),
    ]
